docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: v1/intro.md
    - Reference:
        - 'Dynamic Assertion': v1/dynamic-assertion.md
site_name: zend-expressive-authorization-rbac
site_description: 'RBAC permission adapter for zend-expressive-authorization.'
repo_url: 'https://github.com/zendframework/zend-expressive-authorization-rbac'
