docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: intro.md
site_name: Component Name Goes Here
site_description: 'Component Description goes here'
repo_url: 'https://github.com/mezzio/mezzio-authorization-rbac'
