docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: v1/intro.md
    - Reference:
        - 'Dynamic assertion': v1/dynamic-assertion.md
site_name: mezzio-authorization-rbac
site_description: 'RBAC authorization middleware for Mezzio and PSR-7 applications'
repo_url: 'https://github.com/mezzio/mezzio-authorization-rbac'
